spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true

    properties:
      hibernate:
#        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
#    애플리케이션 시작 시점에 데이터 소스를 초기화하지 않고, 필요한 시점에 초기화
#    하이버네이트보다 data.sql이 먼저 실행되는 것을 방지. spring boot 2.5이상부터는 해당 설정이 필요

  # 서버 실행할 때 data.sql 자동실행
  sql:
    init:
      mode: always

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400